import { Episode } from './types';

export const SJA_EPISODES: Episode[] = [
  // --- TEMPORADA 1 (2007) ---
  {
    id: 'tsja-1-0',
    title: 'SJA 1x00 — Invasion of the Bane (Invasão dos Bane)',
    doctor: 'Sarah Jane Smith',
    year: '2007',
    synopsis: 'Sarah Jane Smith conhece sua nova vizinha, Maria Jackson, e juntas investigam uma fábrica de bebidas chamada Bubble Shock!, descobrindo uma conspiração alienígena e um menino criado em laboratório, Luke.',
    videoUrl: 'https://drive.google.com/open?id=1S3CAh2VleDugbsG2_hdQpC6NAJI73JUm',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 1,
    category: 'spin-off'
  },
  {
    id: 'tsja-1-1',
    title: 'SJA 1x01 — Revenge of the Slitheen - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2007',
    synopsis: 'Maria e Luke começam na nova escola e fazem amizade com Clyde. Eles descobrem que alguns professores são na verdade Slitheens disfarçados planejando apagar o Sol.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsb0lpbmh5dWRkbjQ',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 1,
    category: 'spin-off'
  },
  {
    id: 'tsja-1-2',
    title: 'SJA 1x02 — Revenge of the Slitheen - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2007',
    synopsis: 'As crianças fogem dos Slitheen e se reúnem com Sarah Jane. Eles descobrem que vinagre pode derrotar os alienígenas e tentam impedir o plano catastrófico.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsVERQMWZ3RHlvckk',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 1,
    category: 'spin-off'
  },
  {
    id: 'tsja-1-3',
    title: 'SJA 1x03 — Eye of the Gorgon - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2007',
    synopsis: 'Sarah Jane investiga um asilo supostamente assombrado e descobre um grupo de freiras que escondem uma criatura antiga e alienígena, a Górgona.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsZlpFbndIMkt6N2c',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 1,
    category: 'spin-off'
  },
  {
    id: 'tsja-1-4',
    title: 'SJA 1x04 — Eye of the Gorgon - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2007',
    synopsis: 'A Górgona transforma o pai de Maria em pedra. Sarah Jane e os jovens devem encontrar uma maneira de reverter o processo e selar o portal para outro mundo.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsVzNJSE9WRkx1QWc',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 1,
    category: 'spin-off'
  },
  {
    id: 'tsja-1-5',
    title: 'SJA 1x05 — Warriors of Kudlak - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2007',
    synopsis: 'Jovens começam a desaparecer em um novo centro de laser tag. Luke e Clyde são capturados pelo alienígena Kudlak para lutar em uma guerra interplanetária.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsd0FNc2pTMTgyT2c',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 1,
    category: 'spin-off'
  },
  {
    id: 'tsja-1-6',
    title: 'SJA 1x06 — Warriors of Kudlak - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2007',
    synopsis: 'Sarah Jane descobre que a guerra de Kudlak terminou há anos e tenta convencê-lo a libertar as crianças antes que seja tarde demais.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsT05TZVdVZlBSOXc',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 1,
    category: 'spin-off'
  },
  {
    id: 'tsja-1-7',
    title: 'SJA 1x07 — Whatever Happened to Sarah Jane? - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2007',
    synopsis: 'Sarah Jane desaparece da existência e apenas Maria se lembra dela. Uma mulher chamada Andrea Yates assume seu lugar, tendo feito um pacto com o Trickster.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsREVSRXhTN3dkWlU',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 1,
    category: 'spin-off'
  },
  {
    id: 'tsja-1-8',
    title: 'SJA 1x08 — Whatever Happened to Sarah Jane? - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2007',
    synopsis: 'Maria viaja no tempo para o dia em que Andrea deveria ter morrido para desfazer o pacto e trazer Sarah Jane de volta, enfrentando a manipulação do Trickster.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsaGtlN1NZeGdmTlk',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 1,
    category: 'spin-off'
  },
  {
    id: 'tsja-1-9',
    title: 'SJA 1x09 — The Lost Boy - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2007',
    synopsis: 'Um casal aparece na TV alegando que Luke é seu filho desaparecido, Ashley. Sarah Jane é acusada de sequestro e Luke é levado embora.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsQnlrX0RlNUwyQTg',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 1,
    category: 'spin-off'
  },
  {
    id: 'tsja-1-10',
    title: 'SJA 1x10 — The Lost Boy - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2007',
    synopsis: 'Sarah Jane descobre que os "pais" de Luke são Slitheens disfarçados trabalhando para a Sra. Wormwood. Ela deve resgatar Luke e impedir que ele seja usado como arma.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsUUFMY3FTR2cwSTg',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 1,
    category: 'spin-off'
  },

  // --- TEMPORADA 2 (2008) ---
  {
    id: 'tsja-2-1',
    title: 'SJA 2x01 — The Last Sontaran - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2008',
    synopsis: 'Sarah Jane investiga luzes estranhas em um radiotelescópio e encontra um comandante Sontaran sobrevivente, Kaagh. A família de Maria decide se mudar para a América.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsVXRzYlZOczJ2cXM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 2,
    category: 'spin-off'
  },
  {
    id: 'tsja-2-2',
    title: 'SJA 2x02 — The Last Sontaran - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2008',
    synopsis: 'Kaagh planeja derrubar satélites em instalações nucleares. Sarah Jane e a gangue têm 40 minutos para salvar a Terra e se despedir de Maria.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsdklFcDVydDktaVE',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 2,
    category: 'spin-off'
  },
  {
    id: 'tsja-2-3',
    title: 'SJA 2x03 — The Day of the Clown - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2008',
    synopsis: 'A nova vizinha Rani Chandra é assombrada por um palhaço sinistro. Crianças locais estão desaparecendo e a pista leva a um museu de circo e à lenda do Flautista de Hamelin.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsSTNoTlBTNVNrS1U',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 2,
    category: 'spin-off'
  },
  {
    id: 'tsja-2-4',
    title: 'SJA 2x04 — The Day of the Clown - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2008',
    synopsis: 'Sarah Jane confronta seus próprios medos de infância para derrotar a entidade alienígena que se alimenta do medo das crianças e salvar Luke.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsZ1QyNWtWVS1HbTA',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 2,
    category: 'spin-off'
  },
  {
    id: 'tsja-2-5',
    title: 'SJA 2x05 — Secrets of the Stars - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2008',
    synopsis: 'Um astrólogo chamado Martin Trueman ganha poderes alienígenas e começa a controlar as pessoas através de seus signos do zodíaco.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsaGw4eS1RTzBGdDQ',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 2,
    category: 'spin-off'
  },
  {
    id: 'tsja-2-6',
    title: 'SJA 2x06 — Secrets of the Stars - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2008',
    synopsis: 'Trueman tenta dominar a população mundial. Sarah Jane e Rani devem encontrar uma maneira de quebrar o feitiço das "Luzes Antigas".',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsZzRMRFJfLWt1Nzg',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 2,
    category: 'spin-off'
  },
  {
    id: 'tsja-2-7',
    title: 'SJA 2x07 — The Mark of the Berserker - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2008',
    synopsis: 'Um pingente alienígena que permite controlar os outros é roubado do sótão de Sarah Jane pelo pai distante de Clyde.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsMkFxY0tGalF6TmM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 2,
    category: 'spin-off'
  },
  {
    id: 'tsja-2-8',
    title: 'SJA 2x08 — The Mark of the Berserker - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2008',
    synopsis: 'O pingente começa a transformar o pai de Clyde em um guerreiro Berserker. Clyde deve enfrentar seu pai para salvá-lo e impedir a ameaça.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsN01Icl9ZMnJ4VXM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 2,
    category: 'spin-off'
  },
  {
    id: 'tsja-2-9',
    title: 'SJA 2x09 — The Temptation of Sarah Jane Smith - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2008',
    synopsis: 'Sarah Jane encontra uma fenda temporal para 1951 e tem a chance de salvar seus pais, mas isso faz parte de uma armadilha do Trickster.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsZmdPd2M4NHN1TWs',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 2,
    category: 'spin-off'
  },
  {
    id: 'tsja-2-10',
    title: 'SJA 2x10 — The Temptation of Sarah Jane Smith - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2008',
    synopsis: 'Sarah Jane salva seus pais, mas cria um futuro distópico. Ela deve tomar a decisão impossível de deixá-los morrer para restaurar a linha do tempo.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsSERKc1pXVS13cGM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 2,
    category: 'spin-off'
  },
  {
    id: 'tsja-2-11',
    title: 'SJA 2x11 — Enemy of the Bane - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2008',
    synopsis: 'A Sra. Wormwood retorna pedindo ajuda contra os Bane. Sarah Jane precisa da ajuda do Brigadeiro Lethbridge-Stewart para proteger um artefato antigo.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsT1VWOXlkYUl5eDQ',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 2,
    category: 'spin-off'
  },
  {
    id: 'tsja-2-12',
    title: 'SJA 2x12 — Enemy of the Bane - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2008',
    synopsis: 'Sra. Wormwood e Kaagh se aliam para usar o poder do Horosc. Sarah Jane e o Brigadeiro lutam para impedir a destruição da galáxia.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsTGprSmVYbkxsTDA',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 2,
    category: 'spin-off'
  },

  // --- TEMPORADA 3 (2009) ---
  {
    id: 'tsja-3-1',
    title: 'SJA 3x01 — Prisoner of the Judoon - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2009',
    synopsis: 'Um prisioneiro alienígena perigoso, Androvax, cai na Terra e assume o corpo de Sarah Jane, enquanto os Judoon tentam recapturá-lo.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsVkg4Q1BjamI4Ym8',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 3,
    category: 'spin-off'
  },
  {
    id: 'tsja-3-2',
    title: 'SJA 3x02 — Prisoner of the Judoon - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2009',
    synopsis: 'A gangue deve parar Androvax antes que ele use tecnologia genética para destruir a Terra, enquanto lidam com a jurisdição rígida dos Judoon.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsakdyQWpjdXZ2Vkk',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 3,
    category: 'spin-off'
  },
  {
    id: 'tsja-3-3',
    title: 'SJA 3x03 — The Mad Woman in the Attic - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2009',
    synopsis: 'No ano de 2059, uma Rani idosa relembra o dia em que investigou um demônio em um parque de diversões, revelando a alienígena Eve.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsQzNYa0lyazJ0aHM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 3,
    category: 'spin-off'
  },
  {
    id: 'tsja-3-4',
    title: 'SJA 3x04 — The Mad Woman in the Attic - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2009',
    synopsis: 'Os poderes de Eve saem do controle. Rani deve mudar seu destino para evitar um futuro de solidão e salvar seus amigos.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsd0xVbUd2bmM0QmM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 3,
    category: 'spin-off'
  },
  {
    id: 'tsja-3-5',
    title: 'SJA 3x05 — The Wedding of Sarah Jane Smith - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2009',
    synopsis: 'Sarah Jane está prestes a se casar com Peter Dalton, mas Clyde suspeita que ele esconde algo. O Doutor (10º) aparece para interromper a cerimônia.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsZUxfbkFQcHdOZUU',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 3,
    category: 'spin-off'
  },
  {
    id: 'tsja-3-6',
    title: 'SJA 3x06 — The Wedding of Sarah Jane Smith - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2009',
    synopsis: 'O Trickster é revelado como o arquiteto do casamento. O Doutor e Sarah Jane lutam através de diferentes fusos horários para derrotá-lo.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsM1ZQUU93ZVdyeGM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 3,
    category: 'spin-off'
  },
  {
    id: 'tsja-3-7',
    title: 'SJA 3x07 — The Eternity Trap - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2009',
    synopsis: 'A gangue investiga uma mansão assombrada onde crianças desapareceram séculos atrás, enfrentando o espírito do alquimista Erasmus Darkening.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsT2hQVWV2d29KM1E',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 3,
    category: 'spin-off'
  },
  {
    id: 'tsja-3-8',
    title: 'SJA 3x08 — The Eternity Trap - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2009',
    synopsis: 'Sarah Jane descobre os segredos da tecnologia alienígena de Darkening e tenta libertar as almas presas na mansão.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsaUNCa1JXSnJNVEE',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 3,
    category: 'spin-off'
  },
  {
    id: 'tsja-3-9',
    title: 'SJA 3x09 — Mona Lisa\'s Revenge - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2009',
    synopsis: 'A Mona Lisa ganha vida em uma galeria de arte e começa a transformar pessoas em pinturas, procurando por seu "irmão".',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsSzNaWHdfSWlBa1E',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 3,
    category: 'spin-off'
  },
  {
    id: 'tsja-3-10',
    title: 'SJA 3x10 — Mona Lisa\'s Revenge - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2009',
    synopsis: 'Com Sarah Jane presa, Clyde usa seu talento artístico para enfrentar a Mona Lisa e impedir a libertação de uma abominação antiga.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsakdlQXpRMXBROWM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 3,
    category: 'spin-off'
  },
  {
    id: 'tsja-3-11',
    title: 'SJA 3x11 — The Gift - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2009',
    synopsis: 'Os Blathereen (primos dos Slitheen) oferecem à Terra uma planta que pode acabar com a fome mundial, mas Sarah Jane desconfia de suas intenções.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsQWtseUl2V29yY0k',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 3,
    category: 'spin-off'
  },
  {
    id: 'tsja-3-12',
    title: 'SJA 3x12 — The Gift - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2009',
    synopsis: 'A planta começa a crescer descontroladamente e Luke adoece. Sarah Jane deve encontrar uma cura e impedir que a Terra seja consumida pela flora alienígena.',
    videoUrl: 'https://drive.google.com/open?id=0B5S9UhjV5rpsRURRSENHbHNEWjQ',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 3,
    category: 'spin-off'
  },

  // --- TEMPORADA 4 (2010) ---
  {
    id: 'tsja-4-1',
    title: 'SJA 4x01 — The Nightmare Man - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2010',
    synopsis: 'Luke se prepara para ir à universidade, mas começa a ter pesadelos com uma entidade que quer entrar no mundo real através de seus sonhos.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZMHExcTl0cnZfeUU',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 4,
    category: 'spin-off'
  },
  {
    id: 'tsja-4-2',
    title: 'SJA 4x02 — The Nightmare Man - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2010',
    synopsis: 'Luke, Clyde e Rani estão presos em um mundo de sonhos. Sarah Jane deve lutar sozinha para impedir que o Homem Pesadelo domine a humanidade.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZUjMwSWlpTlFoQkk',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 4,
    category: 'spin-off'
  },
  {
    id: 'tsja-4-3',
    title: 'SJA 4x03 — The Vault of Secrets - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2010',
    synopsis: 'Androvax retorna pedindo ajuda para salvar sua espécie. Eles devem encontrar um cofre secreto vigiado por guardiões androides.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZN1FXN1VFbnZUcU0',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 4,
    category: 'spin-off'
  },
  {
    id: 'tsja-4-4',
    title: 'SJA 4x04 — The Vault of Secrets - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2010',
    synopsis: 'Sarah Jane e Rani lutam contra os androides para abrir o cofre e decidir o destino dos Veil, enquanto a mãe de Rani se envolve na aventura.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZS3hieTFqdXptQnM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 4,
    category: 'spin-off'
  },
  {
    id: 'tsja-4-5',
    title: 'SJA 4x05 — Death of the Doctor - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2010',
    synopsis: 'O Doutor (11º) é declarado morto. Sarah Jane e a ex-companheira Jo Grant se encontram no funeral, mas suspeitam de uma conspiração alienígena.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZNmZoX2x0RU9YNkU',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 4,
    category: 'spin-off'
  },
  {
    id: 'tsja-4-6',
    title: 'SJA 4x06 — Death of the Doctor - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2010',
    synopsis: 'Sarah Jane, Jo e o Doutor enfrentam os Shansheeth. O Doutor leva suas antigas amigas em uma viagem rápida pela TARDIS.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0Zc09Hc1VwblhhMXM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 4,
    category: 'spin-off'
  },
  {
    id: 'tsja-4-7',
    title: 'SJA 4x07 — The Empty Planet - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2010',
    synopsis: 'Clyde e Rani acordam e descobrem que toda a população da Terra desapareceu, restando apenas os dois em uma Londres deserta.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZeVhObUdYUUZwN00',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 4,
    category: 'spin-off'
  },
  {
    id: 'tsja-4-8',
    title: 'SJA 4x08 — The Empty Planet - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2010',
    synopsis: 'Robôs alienígenas chegam para reivindicar o planeta. Clyde e Rani deve trabalhar juntos sem a ajuda de Sarah Jane para trazer todos de volta.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZX3RlWmZLRXE5ck0',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 4,
    category: 'spin-off'
  },
  {
    id: 'tsja-4-9',
    title: 'SJA 4x09 — Lost in Time - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2010',
    synopsis: 'O Enigmático Lojista envia a gangue para diferentes épocas da história para coletar artefatos que podem salvar o futuro.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZMlN5eGZvSjNMVEE',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 4,
    category: 'spin-off'
  },
  {
    id: 'tsja-4-10',
    title: 'SJA 4x10 — Lost in Time - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2010',
    synopsis: 'Sarah Jane enfrenta fantasmas vitorianos, Clyde luta contra nazistas e Rani lida com uma conspiração na era Tudor para salvar a linha do tempo.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZajZqYlNWT0ZVUlU',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 4,
    category: 'spin-off'
  },
  {
    id: 'tsja-4-11',
    title: 'SJA 4x11 — Goodbye, Sarah Jane Smith - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2010',
    synopsis: 'Sarah Jane começa a apresentar sinais de demência e decide se aposentar, entregando suas responsabilidades a uma nova protetora, Ruby White.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZVjhyUzhCNm44eWc',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 4,
    category: 'spin-off'
  },
  {
    id: 'tsja-4-12',
    title: 'SJA 4x12 — Goodbye, Sarah Jane Smith - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2010',
    synopsis: 'Clyde e Rani descobrem que Ruby White é uma alienígena que se alimenta da tristeza. Eles devem salvar Sarah Jane antes que sua essência seja consumida.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZbzhhUk1LbDlycnM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 4,
    category: 'spin-off'
  },

  // --- TEMPORADA 5 (2011) ---
  {
    id: 'tsja-5-1',
    title: 'SJA 5x01 — Sky - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2011',
    synopsis: 'Sarah Jane encontra um bebê abandonado, Sky, que cresce rapidamente. Uma guerra entre duas raças alienígenas, Metalkind e Fleshkind, chega à Terra.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZWW1GdzJiNU5jS0k',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 5,
    category: 'spin-off'
  },
  {
    id: 'tsja-5-2',
    title: 'SJA 5x02 — Sky - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2011',
    synopsis: 'Sky revela ser uma arma biológica. Sarah Jane deve protegê-la e impedir que a guerra alienígena destrua o planeta.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZNktjRmx2OTRNYmM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 5,
    category: 'spin-off'
  },
  {
    id: 'tsja-5-3',
    title: 'SJA 5x03 — The Curse of Clyde Langer - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2011',
    synopsis: 'Clyde é amaldiçoado por um totem antigo e todos os seus amigos e familiares começam a odiá-lo, forçando-o a viver nas ruas.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZbmJGajlwQzQxaHM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 5,
    category: 'spin-off'
  },
  {
    id: 'tsja-5-4',
    title: 'SJA 5x04 — The Curse of Clyde Langer - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2011',
    synopsis: 'Vivendo como sem-teto, Clyde faz uma nova amiga e descobre a verdade sobre a maldição do deus Hetocumtek para quebrar o feitiço.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZYWI3aXpMUjRZLTA',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 5,
    category: 'spin-off'
  },
  {
    id: 'tsja-5-5',
    title: 'SJA 5x05 — The Man Who Never Was - Part 1',
    doctor: 'Sarah Jane Smith',
    year: '2011',
    synopsis: 'A gangue investiga o lançamento de um novo computador revolucionário e descobre que seu criador é na verdade controlado por alienígenas escravizados.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZWFp0dWFTanFuMHM',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 5,
    category: 'spin-off'
  },
  {
    id: 'tsja-5-6',
    title: 'SJA 5x06 — The Man Who Never Was - Part 2',
    doctor: 'Sarah Jane Smith',
    year: '2011',
    synopsis: 'Luke e Sky ajudam a libertar os escravos alienígenas, enquanto Sarah Jane encerra sua última aventura televisionada protegendo a Terra.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZVm42S2h3ajJ2QjA',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 5,
    category: 'spin-off'
  },
  {
    id: 'tsja-5-spec',
    title: 'SJA Especial — My Sarah Jane (Tributo a Elisabeth Sladen)',
    doctor: 'Sarah Jane Smith',
    year: '2011',
    synopsis: 'Um tributo especial à maravilhosa atriz Elisabeth Sladen, celebrando seu eterno legado como Sarah Jane Smith em Doctor Who e em sua própria série.',
    videoUrl: 'https://drive.google.com/open?id=0B0cnJ5ZQGC0ZcXQyc2lpRlgyQ2M',
    poster: 'https://files.catbox.moe/9ia7ps.png',
    parts: 1,
    season: 5,
    category: 'spin-off'
  }
];
